//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2013, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 1K program for KCPSM6 in a 7-Series device using a 
// RAMB18E1 primitive.
//
// Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
//       expansion with minimum changes being required to the hardware description. 
//       Only the lower 10-bits of the address are actually used for the 1K address range
//       000 to 3FF hex.  
//
// Program defined by 'C:\Users\rkravitz\Google Drive\_PSUProjects\ece540f17\botip\firmware\bot31_pgm.psm'.
//
// Generated by KCPSM6 Assembler: 22 Aug 2017 - 11:50:34. 
//
// Assembler used ROM_form template: ROM_form_7S_1K_14March13.v
//
//
module bot31_pgm (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire [17:0] data_in_a;
wire [17:0] data_out_a;
wire [13:0] address_b;
wire [17:0] data_in_b;
wire [17:0] data_out_b;
wire        enable_b;
wire        clk_b;
wire [3:0]  we_b;
//
//
assign address_a = {address[9:0], 4'b1111};
assign instruction = data_out_a[17:0];
assign data_in_a = {16'h0000, address[11:10]};
//
assign address_b = 14'b11111111111111;
assign data_in_b = data_out_b[17:0];
assign enable_b = 1'b0;
assign we_b = 4'h0;
assign clk_b = 1'b0;
//
// 
RAMB18E1 # ( .READ_WIDTH_A              (18),
             .WRITE_WIDTH_A             (18),
             .DOA_REG                   (0),
             .INIT_A                    (16'b000000000000000000),
             .RSTREG_PRIORITY_A         ("REGCE"),
             .SRVAL_A                   (36'h000000000000000000),
             .WRITE_MODE_A              ("WRITE_FIRST"),
             .READ_WIDTH_B              (18),
             .WRITE_WIDTH_B             (18),
             .DOB_REG                   (0),
             .INIT_B                    (36'h000000000000000000),
             .RSTREG_PRIORITY_B         ("REGCE"),
             .SRVAL_B                   (36'h000000000000000000),
             .WRITE_MODE_B              ("WRITE_FIRST"),
             .INIT_FILE                 ("NONE"),
             .SIM_COLLISION_CHECK       ("ALL"),
             .RAM_MODE                  ("TDP"),
             .RDADDR_COLLISION_HWCONFIG ("DELAYED_WRITE"),
             .SIM_DEVICE                ("7SERIES"),
             .INIT_00                   (256'h90000199900701AC00281C401D401E001F0200B1006500472004200420042004),
             .INIT_01                   (256'h01F00F00008302E001F02026E01BC800D031E01BC900B03000280E00006001B2),
             .INIT_02                   (256'hDC02DD010A0001900B00010502C001D0200D01E3180019000C100D0000D302E0),
             .INIT_03                   (256'h400E400E400EE042410EA0200200400E00105000D00ED00ED00CD00CDA03DB04),
             .INIT_04                   (256'hE10011CE1001E10011001001E100110010205000A02002105000300F5000400E),
             .INIT_05                   (256'h5000E100114F1001E10011D81001E10011EE1001E10011CC1001E10011CE1001),
             .INIT_06                   (256'h11421001E10011311001E10011201001E10011171000500000371220310F0100),
             .INIT_07                   (256'h013041065000E10011061001E10011751001E10011641001E10011531001E100),
             .INIT_08                   (256'h00406091D50820B00040608DD50420B000406089D50005200410500000371200),
             .INIT_09                   (256'h20B0007E13000100007E1300014060A0D50D20B0007E130001406097D50C20B0),
             .INIT_0A                   (256'h004020B0007E13010100007E1301014060AFD50F20B0007E1301014060A6D50E),
             .INIT_0B                   (256'hE10011011001E10011111001E10011101001E100111F1001E100110F10105000),
             .INIT_0C                   (256'h400E400E310F0100004412105000E10011FF1001E10011F01001E10011F11001),
             .INIT_0D                   (256'hD10F060020DF960160DED00F60E5D40400CA07C006D0051004205000400E400E),
             .INIT_0E                   (256'h20F5170160F0D10F860020EC160160EBD00F60F2D40820F5071020F5970160E3),
             .INIT_0F                   (256'h500001700060500001C000D060FDD00201000270016050000170006020F58710),
             .INIT_10                   (256'h110104000100920191016117DF000700010002C001D05000900A0000D209D108),
             .INIT_11                   (256'h05000100120104000100920211016125DF015000017B06000100110105000100),
             .INIT_12                   (256'h0100120105000100120104000100920111016133DF025000017B060001001101),
             .INIT_13                   (256'h017B06000100120105000100910104000100120111026141DF035000017B0600),
             .INIT_14                   (256'hDF055000017B0600010091010500010091010400010012011101614FDF045000),
             .INIT_15                   (256'h9101616BDF065000017B0600010091010500010092010400010012029101615D),
             .INIT_16                   (256'h0100920191026179DF075000017B060001009201050001009201040001001201),
             .INIT_17                   (256'h40064006400640060070500010FF5000017B0600010092010500010011010400),
             .INIT_18                   (256'h50005008618FD6025010618CD40250186189D50230F86186D701500740064006),
             .INIT_19                   (256'h1105F1301105F1321101F133110050004010310701F0400640064006400600E0),
             .INIT_1A                   (256'h01901B00180019005000F131F130311F0100F1321107F1331101D000400EF131),
             .INIT_1B                   (256'hB332400E400E4008420E4008410E420E420E420E420E0200310F010050000A00),
             .INIT_1C                   (256'h508009200210E1CEC21021D0D200504008100120E1C7C12021C9D10022302130),
             .INIT_1D                   (256'h01D91219500061DA910101D51128500061D6900110115000400E400E400E400E),
             .INIT_1E                   (256'h930101DE13C8500061E9930101DE1364500061E4930101DE1332500061DF9201),
             .INIT_1F                   (256'h0000000000000000500061F893010330130A500061F3940101ED1405500061EE),
             .INIT_20                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_21                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_22                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_23                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_24                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_25                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_26                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_27                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_28                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_29                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_30                   (256'hD00ED00E01EDD00CD00CDC02DD014C060CD01D01D004900018FF19FF1C001D00),
             .INIT_31                   (256'h0000000000000000000000000000000000000000000000000000000000002304),
             .INIT_32                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_33                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_34                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_35                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_36                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_37                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_38                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_39                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_00                  (256'h5A18618618618280A18618618618218957452AAAA220A008082D748A22802AAA),
             .INITP_01                  (256'h820D82099D67766759DD8025508A1861861861822820DA0DA083683636363428),
             .INITP_02                  (256'h552289249768924976892497689249768924976892497689249768924974820A),
             .INITP_03                  (256'h00B42D8B62D8B62D8B62D25513744DD01555540880A82236222201548D34D345),
             .INITP_04                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_05                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_06                  (256'h00000000000000000000000000000000000000000000000000000002AAA91800),
             .INITP_07                  (256'h0000000000000000000000000000000000000000000000000000000000000000))
 kcpsm6_rom( .ADDRARDADDR               (address_a),
             .ENARDEN                   (enable),
             .CLKARDCLK                 (clk),
             .DOADO                     (data_out_a[15:0]),
             .DOPADOP                   (data_out_a[17:16]), 
             .DIADI                     (data_in_a[15:0]),
             .DIPADIP                   (data_in_a[17:16]), 
             .WEA                       (2'b00),
             .REGCEAREGCE               (1'b0),
             .RSTRAMARSTRAM             (1'b0),
             .RSTREGARSTREG             (1'b0),
             .ADDRBWRADDR               (address_b),
             .ENBWREN                   (enable_b),
             .CLKBWRCLK                 (clk_b),
             .DOBDO                     (data_out_b[15:0]),
             .DOPBDOP                   (data_out_b[17:16]), 
             .DIBDI                     (data_in_b[15:0]),
             .DIPBDIP                   (data_in_b[17:16]), 
             .WEBWE                     (we_b),
             .REGCEB                    (1'b0),
             .RSTRAMB                   (1'b0),
             .RSTREGB                   (1'b0));
//
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE bot31_pgm.v
//
////////////////////////////////////////////////////////////////////////////////////
